pipeline {
    agent any


    stages {
        stage('CLONE') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'main', credentialsId: 'github-privateKey', poll: false, url: 'git@github.com:ElamaranArasu/Server-MCQ.git'
            }
        }
          stage('Build') {
            steps {
                sh 'mvn clean package' // Assuming Maven is installed and configured
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test' // Execute Maven tests
            }
        }

        stage('Notify Git') {
            steps {
                script {
                    // You can add notifications to Git here
                    // For example, using Git publisher plugin or git command
                    // Notify Git that the build is completed
                    sh 'git commit -am "Build completed"'
                    sh 'git push'
                }
            }
        }
    }
        
    
    post {
        success {
            echo 'Build successful! :)'
        }
        failure {
            echo 'Build failed! :('
        }
    }
    
}
